#!/system/bin/sh
#
# Project Vanguard
# Module Context
#

#
# Load Dependencies
#

if [ -z "${CORE_DIR:-}" ]; then
    CORE_DIR="$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)"
fi

. "$CORE_DIR/constants.sh"

#
# Runtime Context
#

VG_CURRENT_MODULE_ID=""
VG_CURRENT_MODULE_NAME=""
VG_CURRENT_MODULE_VERSION=""
VG_CURRENT_MODULE_AUTHOR=""
VG_CURRENT_MODULE_DESCRIPTION=""
VG_CURRENT_MODULE_API=""
VG_CURRENT_MODULE_ENTRY=""
VG_CURRENT_MODULE_PATH=""

#
# Public API
#

vg_context_clear() {

    VG_CURRENT_MODULE_ID=""
    VG_CURRENT_MODULE_NAME=""
    VG_CURRENT_MODULE_VERSION=""
    VG_CURRENT_MODULE_AUTHOR=""
    VG_CURRENT_MODULE_DESCRIPTION=""
    VG_CURRENT_MODULE_API=""
    VG_CURRENT_MODULE_ENTRY=""
    VG_CURRENT_MODULE_PATH=""

    return "$VG_SUCCESS"
}

vg_context_set() {

    VG_CURRENT_MODULE_ID="$VG_MODULE_ID"
    VG_CURRENT_MODULE_NAME="$VG_MODULE_NAME"
    VG_CURRENT_MODULE_VERSION="$VG_MODULE_VERSION"
    VG_CURRENT_MODULE_AUTHOR="$VG_MODULE_AUTHOR"
    VG_CURRENT_MODULE_DESCRIPTION="$VG_MODULE_DESCRIPTION"
    VG_CURRENT_MODULE_API="$VG_MODULE_API"
    VG_CURRENT_MODULE_ENTRY="$VG_MODULE_ENTRY"
    VG_CURRENT_MODULE_PATH="$1"

    return "$VG_SUCCESS"
}
