#
# ==========================================================
# Project Vanguard Configuration
# ==========================================================
#

#
# Logging
#

VG_LOG_LEVEL="INFO"

#
# Detection
#

VG_ENABLE_ROM_CHECK="true"
VG_ENABLE_SELINUX_CHECK="true"

#
# Runtime
#

VG_DEBUG="false"
